### ISSUE TITLE
Cross-platform incompatibility

### ISSUE THREAD

**Issue by derickboss1** [okpy/ok-client#374]
If I run `python3 ok -q [assignment]` on one OS, and then tried to run it again via a different OS, I get the error `dbm.error: db type could not be determined`. Tested by initially running on Windows 10, then running it on linux

The entire error message is:
```
Checking for software updates...
OK is up to date
Traceback (most recent call last):
  File "/usr/lib/python3.7/runpy.py", line 193, in _run_module_as_main
    "__main__", mod_spec)
  File "/usr/lib/python3.7/runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "ok/__main__.py", line 46, in <module>
  File "ok/client/cli/ok.py", line 209, in main
  File "ok/client/protocols/grading.py", line 46, in run
  File "ok/client/protocols/grading.py", line 66, in grade
  File "ok/client/utils/storage.py", line 40, in store
  File "/usr/lib/python3.7/shelve.py", line 243, in open
    return DbfilenameShelf(filename, flag, protocol, writeback)
  File "/usr/lib/python3.7/shelve.py", line 227, in __init__
    Shelf.__init__(self, dbm.open(filename, flag), protocol, writeback)
  File "/usr/lib/python3.7/dbm/__init__.py", line 88, in open
    raise error[0]("db type could not be determined")
dbm.error: db type could not be determined
```

**Comment by mehrdadn** [comment]
@derickboss1 I don't know of a simple fix to this (though perhaps one of the main maintainers might). I would recommend you try to stay on a single platform for now, or find a workaround as mentioned here. Other tools (like git) often also run into trouble if you try to run them cross-platform, so it's a good habit anyway.
