### ISSUE TITLE
 ‎🚨 ‎🚨 ‎🚨 ‎ok-client DOES NOT WORK ON PYTHON 3.8 ‎🚨 ‎🚨 ‎🚨

### ISSUE THREAD

**Issue by kavigupta** [okpy/ok-client#375]
```
=====================================================================
Assignment: Lab 9
OK, version v1.14.15
=====================================================================

Checking for software updates...
OK is up to date
Traceback (most recent call last):
  File "/home/kavi/anaconda3/envs/py38/lib/python3.8/runpy.py", line 192, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "/home/kavi/anaconda3/envs/py38/lib/python3.8/runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "ok/__main__.py", line 46, in <module>
  File "ok/client/cli/ok.py", line 188, in main
  File "ok/client/api/assignment.py", line 24, in load_assignment
  File "ok/client/sources/common/core.py", line 187, in __call__
  File "ok/client/api/assignment.py", line 154, in post_instantiation
  File "ok/client/api/assignment.py", line 264, in _load_protocols
  File "/home/kavi/anaconda3/envs/py38/lib/python3.8/importlib/__init__.py", line 127, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1014, in _gcd_import
  File "<frozen importlib._bootstrap>", line 991, in _find_and_load
  File "<frozen importlib._bootstrap>", line 975, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 655, in _load_unlocked
  File "<frozen importlib._bootstrap>", line 618, in _load_backward_compatible
  File "<frozen zipimport>", line 259, in load_module
  File "ok/client/protocols/testing.py", line 10, in <module>
  File "<frozen importlib._bootstrap>", line 991, in _find_and_load
  File "<frozen importlib._bootstrap>", line 975, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 655, in _load_unlocked
  File "<frozen importlib._bootstrap>", line 618, in _load_backward_compatible
  File "<frozen zipimport>", line 259, in load_module
  File "ok/coverage/__init__.py", line 10, in <module>
  File "<frozen importlib._bootstrap>", line 991, in _find_and_load
  File "<frozen importlib._bootstrap>", line 975, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 655, in _load_unlocked
  File "<frozen importlib._bootstrap>", line 618, in _load_backward_compatible
  File "<frozen zipimport>", line 259, in load_module
  File "ok/coverage/control.py", line 14, in <module>
  File "<frozen importlib._bootstrap>", line 991, in _find_and_load
  File "<frozen importlib._bootstrap>", line 975, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 655, in _load_unlocked
  File "<frozen importlib._bootstrap>", line 618, in _load_backward_compatible
  File "<frozen zipimport>", line 259, in load_module
  File "ok/coverage/html.py", line 8, in <module>
  File "<frozen importlib._bootstrap>", line 991, in _find_and_load
  File "<frozen importlib._bootstrap>", line 975, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 655, in _load_unlocked
  File "<frozen importlib._bootstrap>", line 618, in _load_backward_compatible
  File "<frozen zipimport>", line 259, in load_module
  File "ok/coverage/phystokens.py", line 5, in <module>
  File "<frozen importlib._bootstrap>", line 991, in _find_and_load
  File "<frozen importlib._bootstrap>", line 975, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 655, in _load_unlocked
  File "<frozen importlib._bootstrap>", line 618, in _load_backward_compatible
  File "<frozen zipimport>", line 259, in load_module
  File "ok/coverage/parser.py", line 321, in <module>
  File "ok/coverage/parser.py", line 280, in _opcode
KeyError: 'BREAK_LOOP'
```

**Comment by kavigupta** [comment]
@

**Comment by kavigupta** [comment]
Fixing it for 3.5-3.7 involved reverting the PR that closed this. I am reopening the issue and will work on it a bit over the weekend

**Comment by kavigupta** [comment]
Resolved by https://github.com/okpy/ok-client/pull/384
