### ISSUE TITLE
Deal with race condition in `ok-publish`

### ISSUE THREAD

**Issue by kavigupta** [okpy/ok-client#440]
```
Traceback (most recent call last):
  File "/home/cs61a/course_deploy_files/repo/env/bin/templar", line 11, in <module>
    load_entry_point('templar==2.1.2', 'console_scripts', 'templar')()
  File "/home/cs61a/course_deploy_files/repo/env/lib/python3.6/site-packages/templar/cli/templar.py", line 70, in main
    run(flags())
  File "/home/cs61a/course_deploy_files/repo/env/lib/python3.6/site-packages/templar/cli/templar.py", line 56, in run
    no_write=args.print)
  File "/home/cs61a/course_deploy_files/repo/env/lib/python3.6/site-packages/templar/api/publish.py", line 105, in publish
    os.makedirs(destination_dir)
  File "/usr/lib/python3.6/os.py", line 220, in makedirs
    mkdir(name, mode)
```

**Comment by kavigupta** [comment]
Oh wait this is a templar issue, whoops
